# Generated by Django 5.0.1 on 2024-05-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creamy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='name',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
