# Generated by Django 5.0.1 on 2024-05-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creamy', '0002_alter_weight_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
